post:
  operationId: upload
  summary: upload an application to enterprise
  description: Returns application
  produces:
    - application/json
  parameters:
    - name: enterprise
      description: enterprise id
      in: formData
      required: true
      type: string
      format: uuid
    - name: app_file
      description:  valid APK file
      in: formData
      required: true
      type: file
  responses:
    '201':
      description: successful operation
      schema:
        $ref: '#/definitions/Application'
  consumes:
    - multipart/form-data
    - application/x-www-form-urlencoded
  tags:
    - Enterprise Application
parameters:
  - name: enterprise_id
    description: A UUID string identifying this enterprise.
    in: path
    required: true
    type: string